== Playbooks to configure OpenShift 4.x cluster


Couple of ansible roles to configure serveral components for a freshly intalled
openshift cluster. Typical configurations that need to be performed are


* setup ldap oauth
* sync user groups from ldap to openshift
* etc..

IMPORTANT: None of these role are written to be used blindly. They are provided
as a POC/ minimum viable option to get you kickstarted without having to put an
effort to figure out exactly what all needs to be done.

A lot of assumptions are made.
So please walk through the roles first, before attempting to run them.

=== Runing the indivdual roles
You can run individual roles by runnning ansible playbook against the
<role>/apply/main.yaml playbook in each of the individual roles.

----
ansible-playbook roles/<role-name>/apply/main.yaml
----

=== Setting up LDAP

==== LDAP oAuth
The ldap-oauth role handles configuring the default identity providers for the cluster. An OCP cluster can have multiple identity providers eg: LDAP oAuth and a htpasswd file etc. Ours clusters are setup to have just the ldap oauth identiy provider.

[source,bash]
----
ansible-playbook roles/ldap-oauth/apply/main.yml -e ldap_bind_password=<ldap-service-account-password>
----
[NOTE]
The extra variable ldap_bind_password will not be required once we have the creds being pulled from secret server

==== LDAP to OCP group synchronisation
The ldap-group-sync role handles synchornising a whitelisted set of AD groups to the OpenShift cluster.

[source,bash]
----
ansible-playbook roles/ldap-group-sync/apply/main.yml
----

=== Setting up Trident csi for OpenShift 4.x
The role here is just a skeleton or sample.
It needs a lot of work to make it a more generic role to be used for any
tridnt installation. Then again the number of variable or parameters that will
need to be passed to the role will be quite a lot so ¯\_(ツ)_/¯

[source,bash]
----
ansible-playbook roles/trident/apply/main.yml
----
