== cluster-logging
This role configures cluster-logging as per the Openshift documenation.
I try to follow allon closely the steps documented in the below page.

https://docs.openshift.com/container-platform/4.3/logging/cluster-logging-deploying.html

The playbooks create the necessary namespaces, create subscriptions, install the
operators and finally pushes out a CR for ClusterLogging.

=== Role Variables
Default role variables that are defined.

```
clo_elastic_storage_size: "500Gi"
clo_elastic_redundancyPolicy: "SingleRedundancy"
clo_elastic_nodeCount: 3
```

=== Dependencies
This ansible role requires that you are have an authenticated kubectl session
which has sufficient previlegges to create namespaces, and install operators.


=== Example Usage
Example invocation of the role in a playbook

[source,yaml]
----
- hosts: localhost
  tasks:
    - include_role:
        name: cluster-logging
----

OR if you want to override some default variables

[source,yaml]
----
- hosts: localhost
  tasks:
    - include_role:
        name: cluster-logging
      vars:
        clo_elastic_storage_size: "1000Gi"
----

If you would like to use the role without including it or writing a playbook,
from the root of this github repo you can run the following.

[source,bash]
----
ansible-playbook roles/cluster-logging/apply/main.yml \
                 -e clo_elastic_storage_size=1000Gi
----


TODO:

  - Need to explore using taints/tolerations instead of nodeSelector
    The docs seem to be moving away from using nodeSelector
