- name: Setting the master nodes are not schedulable
  k8s:
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: Scheduler
      metadata:
        name: cluster
      spec:
        mastersSchedulable: false
