kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: "vsphere-csi"
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  storagepolicyname: "OCP-Storage-Policy"
  fstype: ext4
