== Useful Scripts

=== check-upgrade-path.sh

The `check-upgrade-path.sh` scriptcan be used to check the upgrade path that
are available for you cluster. You need to provide the version of the cluster
as well as the channel you are subribed to (or plan to subscribe to)

This scrip was primarily created to help decide which version of OCP to upgrade
to when running a disconnected / air gapped OCP cluster. Ofcourse you need to
run this script from a machine that has internet
connectivty or access to hit https://api.openshift.com/

Reference:

- link:https://access.redhat.com/solutions/4583231[OpenShift Container Platform (OCP) 4 upgrade paths]
- link:https://access.redhat.com/solutions/4606811[How to Upgrade OpenShift 4 between different minor versions via "oc" cli]
- link:https://www.ocp-upgrade.net/[OpenShift Upgrade Path - Graphs]

**Example - 1 :**

OpenShift 4.3.0 on stable-4.3

```bash
Sushils-MacBook-Pro:scripts sushil$ ./check-upgrade-path.sh --ocp-version 4.3.0 --channel stable-4.3
[
  "4.3.18",
  "4.3.28"
]
```

From the output you can see that you can upgrade to 4.3.18 or 4.3.28


**Example - 2 :**

Uprade options for OCP 4.3.18 on stable-4.3 channel

```bash
Sushils-MacBook-Pro:scripts sushil$ ./check-upgrade-path.sh --ocp-version 4.3.18 --channel stable-4.3
[
  "4.3.19",
  "4.3.21",
  "4.3.22",
  "4.3.23",
  "4.3.25",
  "4.3.26",
  "4.3.27",
  "4.3.28"
]
```

As you can see there are several options that you can upgrade to. I would
personally move up to the highest possibke version which is 4.3.28

**Example - 3 :**

Upgrading OCP 4.3.18 on stable-4.4 channel

```bash
Sushils-MacBook-Pro:scripts sushil$ ./check-upgrade-path.sh --ocp-version 4.3.18 --channel stable-4.4
[
  "4.3.19",
  "4.3.21",
  "4.3.22",
  "4.3.23",
  "4.3.25",
  "4.3.26",
  "4.3.27",
  "4.3.28",
  "4.4.4",
  "4.4.5",
  "4.4.6",
  "4.4.9"
]
```

From the output you can see that you can upgrade directly to OCP 4.4.9
provided you are switch to the stable-4.4 channel.

**Example - 4 :**
Hang on a second. Could I have then upgrade OCP 4.3.0 directly to OCP 4.4.x if
I make use of the stable-4.4 channel ?

``` bash
Sushils-MacBook-Pro:scripts sushil$ ./check-upgrade-path.sh --ocp-version 4.3.0 --channel stable-4.4
[]
```

The answer is NO, you cannot upgrade (shouldn't try/froce) from OCP 4.3.0 to
OCP 4.4.x directly in one step.

**Example - 5 :**
OpenShift 4.5.1 just got released can I upgrade OCP 4.4.8 directly to
OCP 4.5.1 ?

```bash
Sushils-MacBook-Pro:scripts sushil$ ./check-upgrade-path.sh --ocp-version 4.4.8 --channel stable-4.5
[]
```

Even though OCP 4.5.1 is available in the stable-4.5 channel it is still not
avaialble as an upgrade path for OCP 4.4.x yet. Once the upgrade has been made
available for 4.4.x release it will show up and tell you which version of
OCP 4.5.x it is safe to upgrade to.

