== Useful Scripts

=== check-upgrade-path.sh

The `check-upgrade-path.sh` scriptcan be used to check the upgrade path that
are available for you cluster. You need to provide the version of the cluster
as well as the channel you are subribed to (or plan to subscribe to)

This scrip was primarily created to help decide which version of OCP to upgrade
to when running a disconnected / air gapped OCP cluster. Ofcourse you need to
run this script from a machine that has internet
connectivty or access to hit https://api.openshift.com/

Reference:

- link:https://access.redhat.com/solutions/4583231[OpenShift Container Platform (OCP) 4 upgrade paths]
- link:https://access.redhat.com/solutions/4606811[How to Upgrade OpenShift 4 between different minor versions via "oc" cli]
- link:https://www.ocp-upgrade.net/[OpenShift Upgrade Path - Graphs]

**Example - 1 :**

OpenShift 4.3.0 on stable-4.3

```bash
Sushils-MacBook-Pro:scripts sushil$ ./check-upgrade-path.sh --ocp-version 4.3.0 --channel stable-4.3
[
  "4.3.18",
  "4.3.28"
]
```

From the output you can see that you can upgrade to 4.3.18 or 4.3.28


**Example - 2 :**

Uprade options for OCP 4.3.18 on stable-4.3 channel

```bash
Sushils-MacBook-Pro:scripts sushil$ ./check-upgrade-path.sh --ocp-version 4.3.18 --channel stable-4.3
[
  "4.3.19",
  "4.3.21",
  "4.3.22",
  "4.3.23",
  "4.3.25",
  "4.3.26",
  "4.3.27",
  "4.3.28"
]
```

As you can see there are several options that you can upgrade to. I would
personally move up to the highest possibke version which is 4.3.28

**Example - 3 :**

Upgrading OCP 4.3.18 on stable-4.4 channel

```bash
Sushils-MacBook-Pro:scripts sushil$ ./check-upgrade-path.sh --ocp-version 4.3.18 --channel stable-4.4
[
  "4.3.19",
  "4.3.21",
  "4.3.22",
  "4.3.23",
  "4.3.25",
  "4.3.26",
  "4.3.27",
  "4.3.28",
  "4.4.4",
  "4.4.5",
  "4.4.6",
  "4.4.9"
]
```

From the output you can see that you can upgrade directly to OCP 4.4.9
provided you are switch to the stable-4.4 channel.

**Example - 4 :**
Hang on a second. Could I have then upgrade OCP 4.3.0 directly to OCP 4.4.x if
I make use of the stable-4.4 channel ?

``` bash
Sushils-MacBook-Pro:scripts sushil$ ./check-upgrade-path.sh --ocp-version 4.3.0 --channel stable-4.4
[]
```

The answer is NO, you cannot upgrade (shouldn't try/froce) from OCP 4.3.0 to
OCP 4.4.x directly in one step.

**Example - 5 :**
OpenShift 4.5.1 just got released can I upgrade OCP 4.4.8 directly to
OCP 4.5.1 ?

```bash
Sushils-MacBook-Pro:scripts sushil$ ./check-upgrade-path.sh --ocp-version 4.4.8 --channel stable-4.5
[]
```

Even though OCP 4.5.1 is available in the stable-4.5 channel it is still not
avaialble as an upgrade path for OCP 4.4.x yet. Once the upgrade has been made
available for 4.4.x release it will show up and tell you which version of
OCP 4.5.x it is safe to upgrade to.

=== regen-system-admin-kubeconfig.sh

Regnerates a new kubeconfig for the system:admin user. When a fresh OpenShift
installation is done, the installer leaves behind a kubeconfig file for the
`system:admin` user that has full cluster-admin privileges.

There are several reasons why would you want to recreate this kubeconfig.

* You accidentally deleted/lost the original kubeconfig generated by the
  installer.
* You have deployed custom certificates singned by your internal PKI
  infrastructure. Now your original kubeconfig doesn't work any more.

IMPORTANT: This script assumes you have an logged in session for a cluster
           admin user account, possibly an Identity backed user account.
           (eg: an LDAP autenticated user)

Steps take by the script can be summarised as

* Create a openssl config file containing the OU, CN answers.
* Generate a new key and csr for the user `system:admin`
* Create a k8s CertificateSigningRequest object with the newly generated csr
* Approve the new csr request in k8s
* Extract the signed certficate form the approved csr object in k8s
* Extract the CA certifcates in use by the OCP cluster
* Generate a new kuybeconfig with cluster's CA and the user key and newly signed certificate.

**Example usage:**

Generating a newly kubeconfig for `system:admin` user
```bash
Sushils-MacBook-Pro:temp sushil$ ./regen-system-admin-kubeconfig.sh

Generating openssl config file to create a new cert key and csr
Generating new certifcate key and csr for system:admin user
Generating a RSA private key
...................................+++++
...............+++++
writing new private key to 'system-admin.key'
-----
Creating a CertificateSigningRequest yaml file
Create a new CertificateSigningRequest object for system:admin user
certificatesigningrequest.certificates.k8s.io/system-admin-csr created
Approve the newly requested certificate for system:admin user
certificatesigningrequest.certificates.k8s.io/system-admin-csr approved
Extract the newly signed certificate for system:admin user
Deleting the approved csr request
certificatesigningrequest.certificates.k8s.io "system-admin-csr" deleted
Extracing CA certs from the cluster
Generate a new kubeconfig for system:admin user

        Newly created kubeconfig file is save as - "system-admin-kubeconfig"

Deleting temporary files.
```

Testing the newly created kubeconfig
```bash
Sushils-MacBook-Pro:temp sushil$ ls -l
total 20
-rwxrwxr-x 1 sushil staff 4993 Sep 20 09:47 regen-system-admin-kubeconfig.sh
-rw-rw-r-- 1 sushil staff 9234 Sep 20 09:44 system-admin-kubeconfig

Sushils-MacBook-Pro:temp sushil$ export KUBECONFIG=system-admin-kubeconfig
Sushils-MacBook-Pro:temp sushil$ oc whoami
system:admin
```

NOTE: If you would like to inspect the temporary files being created by the
      script you can run with the `--debug` option and it will leave all the
      temp files behind.

```bash
Sushils-MacBook-Pro:temp sushil$ ./regen-system-admin-kubeconfig.sh --debug


Sushils-MacBook-Pro:temp sushil$ ls -l
total 44
-rw-rw-r-- 1 sushil staff 1485 Sep 20 09:59 CertificateSigningRequest.yaml
-rw-rw-r-- 1 sushil staff 3560 Sep 20 09:59 ocp-ca.crt
-rwxrwxr-x 1 sushil staff 4993 Sep 20 09:47 regen-system-admin-kubeconfig.sh
-rw-rw-r-- 1 sushil staff 1237 Sep 20 09:59 system-admin.crt
-rw-rw-r-- 1 sushil staff  928 Sep 20 09:59 system-admin.csr
-rw-rw-r-- 1 sushil staff  291 Sep 20 09:59 system-admin-csr.conf
-rw------- 1 sushil staff 1704 Sep 20 09:59 system-admin.key
-rw-rw-r-- 1 sushil staff 9234 Sep 20 09:59 system-admin-kubeconfig
```
