== splunk-connect
This role configures an OpenShift cluster to forward logs to a splunk endpoint
using splunk-connect.

This role was setup based on splunk connect for kubernetes.
https://github.com/splunk/splunk-connect-for-kubernetes

Please *DO NOT* use the role as is.

IMPORTANT: splunk-connect project is fast moving.
This role was last updated with splunk-connect version *1.4.1*
Always fetch the latest version from the upstream splunk-connect git repo.

=== How were the templates in the templates folder generated ?
I chose to use helm 3 , which mean i did not have to worry about setting up
tiller. (helm 3 was released just 3 days before this role was created)

- Create a my_values.yaml file containing config parameters
- run helm template to genereate the templates

```
mkdir splunk-connect
helm template splunk-connect \
     -f splunk-connect-config.yaml \
     https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.4.1/splunk-connect-for-kubernetes-1.4.1.tgz \
     --output-dir ./splunk-connect

```

=== Contents of splunk-connect-config.yaml vars file
You will find a copy checked into the git repo as well.
```
global:
  logLevel: info
  splunk:
    hec:
      host: splunk.example.com
      port: 8088
      protocol: https
      insecureSSL: true
  kubernetes:
    clusterName: "opentlc"
    openshift: true

splunk-kubernetes-logging:
  enabled: true
  splunk:
    hec:
      indexName: container-logs
      token: 5d4a219a-46dd-4da8-b6e4-3b810d685c72
  containers:
    logFormatType: cri
    logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
  serviceAccount:
    create: true

splunk-kubernetes-objects:
  enabled: true
  splunk:
    hec:
      indexName: k8s-objects
      token: eb0771d7-7f78-4ef3-9825-acd94120b51b
  serviceAccount:
    create: true

splunk-kubernetes-metrics:
  enabled: false
```

=== Dependencies
Helm3 command line utility installed to generate your templates.

=== Assumptions
you are comforatable replacing config settings form the template to be
variables that can be substituted.

